import { mkdir, writeFile } from "node:fs/promises";
import { resolve, join } from "node:path";
import { requireOption, type ParsedArgs } from "../args.js";

export async function runScaffoldPack(args: ParsedArgs): Promise<void> {
  const name = args.positional[0] ?? requireOption(args, "name");
  const outDir = (args.options["dir"] as string | undefined) ?? "./packages";
  const target = resolve(outDir, name);

  const safeName = name.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
  const pkgName = `@content-gen/${safeName}`;

  await mkdir(join(target, "src"), { recursive: true });

  await writeFile(
    join(target, "package.json"),
    JSON.stringify(
      {
        name: pkgName,
        version: "0.1.0",
        type: "module",
        main: "./dist/index.js",
        types: "./dist/index.d.ts",
        exports: {
          ".": { types: "./dist/index.d.ts", import: "./dist/index.js" },
        },
        files: ["dist", "src", "README.md"],
        sideEffects: false,
        scripts: { build: "tsc -b", typecheck: "tsc --noEmit" },
        dependencies: {
          "@content-gen/core": "workspace:*",
          "@content-gen/grammar": "workspace:*",
        },
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );

  await writeFile(
    join(target, "tsconfig.json"),
    JSON.stringify(
      {
        extends: "../../tsconfig.base.json",
        compilerOptions: {
          outDir: "./dist",
          rootDir: "./src",
          paths: {
            "@content-gen/core": ["../core/src/index.ts"],
            "@content-gen/grammar": ["../grammar/src/index.ts"],
          },
        },
        include: ["src/**/*"],
        exclude: ["src/**/*.test.ts", "dist"],
        references: [{ path: "../core" }, { path: "../grammar" }],
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );

  await writeFile(
    join(target, "src", "index.ts"),
    `import { type Generator, oneOf } from "@content-gen/core";
import { grammar } from "@content-gen/grammar";

export const example: Generator<string> = grammar({
  start: "Hello, #name#!",
  name: ["world", "${name}"],
}, { id: "${safeName}.example" });

export const generators = { example } as const;
`,
    "utf8",
  );

  await writeFile(
    join(target, "README.md"),
    `# ${pkgName}\n\nGenerated by \`content-gen scaffold-pack\`.\n`,
    "utf8",
  );

  console.log(`[scaffold-pack] created ${pkgName} at ${target}`);
  console.log(`[scaffold-pack] add { "path": "./packages/${name}" } to root tsconfig.json references`);
  console.log(`[scaffold-pack] then run: pnpm install`);
}
